### ISSUE TITLE
Pando test failure

### ISSUE THREAD

**Issue by prdoyle** [venasolutions/bosk#95]
[This test](https://github.com/venasolutions/bosk/actions/runs/7670315670/job/20906196858) failed on SHA 678484a90a665f663631d7dc9b19d97af4e1ed21.

Symptom:

```
MongoDriverRecoveryTest > databaseDropped_recovers() > [1] {flushOrWait=FLUSH, parameters=MongoDriverRecoveryTest_1_PandoFormat} FAILED
    org.opentest4j.AssertionFailedError: expected: <TestEntity(id=root, string=after drop, catalog={123=TestEntity(id=123, string=123, catalog={}, listing=/catalog/123/catalog/[], sideTable=/catalog/123/catalog/{}, values=Optional.empty), 124=TestEntity(id=124, string=124, catalog={}, listing=/catalog/124/catalog/[], sideTable=/catalog/124/catalog/{}, values=Optional.empty)}, listing=/catalog/[123], sideTable=/catalog/{}, values=Optional.empty)> but was: <TestEntity(id=root, string=before disruption, catalog={123=TestEntity(id=123, string=123, catalog={}, listing=/catalog/123/catalog/[], sideTable=/catalog/123/catalog/{}, values=Optional.empty), 124=TestEntity(id=124, string=124, catalog={}, listing=/catalog/124/catalog/[], sideTable=/catalog/124/catalog/{}, values=Optional.empty)}, listing=/catalog/[123], sideTable=/catalog/{}, values=Optional.empty)>
```

[logs_367.zip](https://github.com/venasolutions/bosk/files/14066958/logs_367.zip)

**Comment by prdoyle** [comment]
Stack trace:

```
MongoDriverRecoveryTest > databaseDropped_recovers() > [1] {flushOrWait=FLUSH, parameters=MongoDriverRecoveryTest_1_PandoFormat} FAILED
    org.opentest4j.AssertionFailedError: expected: <TestEntity(id=root, string=after drop, catalog={123=TestEntity(id=123, string=123, catalog={}, listing=/catalog/123/catalog/[], sideTable=/catalog/123/catalog/{}, values=Optional.empty), 124=TestEntity(id=124, string=124, catalog={}, listing=/catalog/124/catalog/[], sideTable=/catalog/124/catalog/{}, values=Optional.empty)}, listing=/catalog/[123], sideTable=/catalog/{}, values=Optional.empty)> but was: <TestEntity(id=root, string=before disruption, catalog={123=TestEntity(id=123, string=123, catalog={}, listing=/catalog/123/catalog/[], sideTable=/catalog/123/catalog/{}, values=Optional.empty), 124=TestEntity(id=124, string=124, catalog={}, listing=/catalog/124/catalog/[], sideTable=/catalog/124/catalog/{}, values=Optional.empty)}, listing=/catalog/[123], sideTable=/catalog/{}, values=Optional.empty)>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
        at app//io.vena.bosk.drivers.mongo.MongoDriverRecoveryTest.testRecovery(MongoDriverRecoveryTest.java:293)
        at app//io.vena.bosk.drivers.mongo.MongoDriverRecoveryTest.databaseDropped_recovers(MongoDriverRecoveryTest.java:137)
```

**Comment by prdoyle** [comment]
I got a failure with debug logs [here](https://github.com/prdoyle/bosk/actions/runs/7711661028/job/21017460180):
[logs_634.zip](https://github.com/venasolutions/bosk/files/14098365/logs_634.zip)

**Comment by prdoyle** [comment]
I have a branch with some fixes [here](https://github.com/prdoyle/bosk/commits/try-pando-failure/).

**Comment by prdoyle** [comment]
I saw it fail twice in 26 runs, so I'd like to see at least 65 passing runs [here](https://github.com/prdoyle/bosk/actions/runs/7718585408) before declaring success.

After that, I can clean up the branch and re-enable all tests, and see if I can survive a few dozen runs with no failures. 🤞

**Comment by prdoyle** [comment]
Rerunning the single test [here](https://github.com/prdoyle/bosk/actions/runs/7718585408), and the full suite on the PR [here](https://github.com/prdoyle/bosk/actions/runs/7719910478).

**Comment by prdoyle** [comment]
Passed the [single test](https://github.com/prdoyle/bosk/actions/runs/7718585408) 101 times with no failures. I would have expected about 7 failures if the bug were present, so it's safe to say the bug is fixed.

I'm planning to run the [full suite](https://github.com/prdoyle/bosk/actions/runs/7719910478) on repeat overnight to ensure I didn't break anything else.

**Comment by prdoyle** [comment]
Welp, it didn't run overnight... but it did pass 16 times with no failures. I'm going to call that a victory.
